### ISSUE TITLE
BuildConfigFromConfigFile. Could not load file or assembly System.Text.Json, Version=7.0.0.0

### ISSUE THREAD

**Issue by ryee0701** [kubernetes-client/csharp#1158]
**Describe the bug**
I am develop in Azure Functions. AzureFunctionsVersion v4
Then just error in build config
`var config = KubernetesClientConfiguration.BuildConfigFromConfigFile("C:\\Users\\10907042\\.kube\\config");`
error message below in Additional context

both I add package manually or not, all fail
`dotnet add package System.Text.Json --version 7.0.0.0`
or
`dotnet add package System.Text.Json --version 7.0.1.0`

Same code in Kubernetes C# SDK Client Version in 1.5.18 everything is right.

**Kubernetes C# SDK Client Version**
I test in 10.0.1 and 9.1.3

**Server Kubernetes Version**
1.23.8

**Dotnet Runtime Version**
net 6.0.300

**To Reproduce**

**Expected behavior**

**KubeConfig**

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Windows 10
 - Environment Azure Functions Debug mode
 - Cloud Azure

**Additional context**
Error:
`[2022-12-29T06:13:41.002Z] ea38c585920a4d198b6defcf6522bf9e: Function 'DurableFunctionsOrchestration (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'Common_ScanNode' failed: "The type initializer for 'k8s.KubernetesYaml' threw an exception.". See the function execution logs for additional details.
[2022-12-29T06:13:41.003Z]  ---> System.TypeInitializationException: The type initializer for 'k8s.KubernetesYaml' threw an exception.
[2022-12-29T06:13:41.004Z]  ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 系統找不到指定的 
檔案。
[2022-12-29T06:13:41.005Z] File name: 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
[2022-12-29T06:13:41.006Z]    at k8s.KubernetesYaml.WithOverridesFromJsonPropertyAttributes[TBuilder](TBuilder builder)
[2022-12-29T06:13:41.006Z]    at k8s.KubernetesYaml..cctor()
[2022-12-29T06:13:41.007Z]    --- End of inner exception stack trace ---
[2022-12-29T06:13:41.008Z]    at k8s.KubernetesYaml.GetDeserializer(Boolean strict)
[2022-12-29T06:13:41.009Z]    at k8s.KubernetesYaml.Deserialize[TValue](String yaml, Boolean strict)
[2022-12-29T06:13:41.009Z]    at k8s.KubernetesYaml.LoadFromStreamAsync[T](Stream stream, Boolean strict)
[2022-12-29T06:13:41.010Z]    at k8s.KubernetesClientConfiguration.LoadKubeConfigAsync(FileInfo kubeconfig, Boolean useRelativePaths)
[2022-12-29T06:13:41.011Z]    at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
[2022-12-29T06:13:41.012Z]    at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
[2022-12-29T06:13:41.013Z]    at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)`

**Comment by tg123** [comment]
you can test with 9.0.x while i am testing with az func

**Comment by tg123** [comment]
worked per my test, could you please share you settings?
```
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
```

**Comment by ryee0701** [comment]
> worked per my test, could you please share you settings?
> 
> ```
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <AzureFunctionsVersion>v4</AzureFunctionsVersion>
>   </PropertyGroup>
>   <ItemGroup>
>     <PackageReference Include="KubernetesClient" Version="10.0.1" />
>     <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
>   </ItemGroup>
> ```

much thanks for the reply. I will test soon and share my setting when I back to company after my holiday end. the testing code not on cloud. Sorry about that.

**Comment by ryee0701** [comment]
> worked per my test, could you please share you settings?
> 
> ```
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <AzureFunctionsVersion>v4</AzureFunctionsVersion>
>   </PropertyGroup>
>   <ItemGroup>
>     <PackageReference Include="KubernetesClient" Version="10.0.1" />
>     <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
>   </ItemGroup>
> ```

@tg123 setting below. Then I test KubernetesClient version 9.0.38, it work, thanks! I can use this version for my task.
But what cause it? Will it fix in new version? or what should I do when I use new version in future? 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="6.4.2" />
    <PackageReference Include="KubernetesClient" Version="9.0.38" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.7.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.9" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.4.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.6" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by ryee0701** [comment]
when I change version to 9.0.38. It error "sometimes" like http/2 issue in #1112 
old version http2 error, new version can not build config, what could I do :( 
 ```
[2023-01-03T05:16:12.798Z] System.Private.CoreLib: Exception while executing function: Common_ScanPod. System.Private.CoreLib: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
[2023-01-03T05:16:12.842Z] f0cf9dae50f24c269693eaa453cb97d6: Function 'Common_ScanPod (Activity)' failed with an error. Reason: System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
[2023-01-03T05:16:12.847Z]    at System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(Http2Connection connection, Boolean isNewConnection)
[2023-01-03T05:16:12.848Z]    at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
[2023-01-03T05:16:12.848Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[2023-01-03T05:16:12.849Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-03T05:16:12.850Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[2023-01-03T05:16:12.852Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[2023-01-03T05:16:12.853Z]    at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[2023-01-03T05:16:12.854Z]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[2023-01-03T05:16:12.855Z]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[2023-01-03T05:16:12.855Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-01-03T05:16:12.856Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-03T05:16:12.857Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[2023-01-03T05:16:12.858Z]    at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[2023-01-03T05:16:12.859Z]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[2023-01-03T05:16:12.860Z]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[2023-01-03T05:16:12.860Z]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[2023-01-03T05:16:12.861Z]    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
[2023-01-03T05:16:12.862Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[2023-01-03T05:16:12.863Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-03T05:16:12.864Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[2023-01-03T05:16:12.864Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[2023-01-03T05:16:12.865Z]    at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[2023-01-03T05:16:12.866Z]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[2023-01-03T05:16:12.867Z]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[2023-01-03T05:16:12.868Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[2023-01-03T05:16:12.869Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
[2023-01-03T05:16:12.870Z]    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
[2023-01-03T05:16:12.871Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-03T05:16:12.872Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[2023-01-03T05:16:12.872Z]    at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[2023-01-03T05:16:12.873Z]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[2023-01-03T05:16:12.874Z]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[2023-01-03T05:16:12.875Z]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[2023-01-03T05:16:12.876Z]    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
[2023-01-03T05:16:12.877Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-03T05:16:12.877Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[2023-01-03T05:16:12.878Z]    at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[2023-01-03T05:16:12.879Z]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[2023-01-03T05:16:12.880Z]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[2023-01-03T05:16:12.881Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[2023-01-03T05:16:12.881Z]    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
[2023-01-03T05:16:12.883Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-01-03T05:16:12.884Z]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[2023-01-03T05:16:12.885Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
[2023-01-03T05:16:12.886Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
[2023-01-03T05:16:12.887Z]    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
[2023-01-03T05:16:12.888Z] --- End of stack trace from previous location ---
[2023-01-03T05:16:12.889Z]    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[2023-01-03T05:16:12.889Z]    at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-01-03T05:16:12.890Z]    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[2023-01-03T05:16:12.891Z]    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-01-03T05:16:12.892Z]    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-01-03T05:16:12.893Z]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[2023-01-03T05:16:12.894Z]    at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
[2023-01-03T05:16:12.894Z]    at k8s.AbstractKubernetes.k8s.ICoreV1Operations.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, 
String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
[2023-01-03T05:16:12.895Z]    at k8s.CoreV1OperationsExtensions.ListNamespacedPodAsync(ICoreV1Operations operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, 
String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, CancellationToken cancellationToken)
[2023-01-03T05:16:12.896Z]    at k8s.CoreV1OperationsExtensions.ListNamespacedPod(ICoreV1Operations operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty)
```

**Comment by tg123** [comment]
I tested your proj and it works with 10.x

the err you get is likely due to `system.json` was upgraded to 7.x after 9.1+.
however, it should be good as system.json 7 supports net6 as well


could you please check your os version? that is only on windows 8, i do not think func app is still using win8. 

![image](https://user-images.githubusercontent.com/170430/210325150-1669ae81-2a79-4299-a1e3-2bd375537f78.png)

**Comment by ryee0701** [comment]
@tg123
I am not use the functions (SAAS)service on azure. I will use functions framework and build with docker then deploy to AKS(not yet).
But the error is happen when I debug in local machine(windows 10) on debug mode(not with docker)
the other thing may make different is I am using DurableFunctions

the vs code launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to .NET Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:azureFunctions.pickProcess}"
        }
    ]
}
```

**Comment by ryee0701** [comment]
I put it on AKS today, dockerfile below
another err found..like the origin err I post
why it always load specific version not like >= or something I misunderstand..
I add package manually.It say package downgrade from 17.2.3...


error message
```
failed: \"Could not load file or assembly 'System.IO.Abstractions, Version=17.0.0.0, Culture=neutral, PublicKeyToken=96bf224d23c43e59'. The system cannot find the file specified.\n\".
```

dockerfile
```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env

# Build requires 3.1 SDK
COPY --from=mcr.microsoft.com/dotnet/core/sdk:3.1 /usr/share/dotnet /usr/share/dotnet

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj -c Release --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:4-appservice
FROM mcr.microsoft.com/azure-functions/dotnet:4
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        zlib1g \
        fontconfig \
        libfreetype6 \
        libx11-6 \
        libxext6 \
        libxrender1 \
        libgdiplus

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
```

**Comment by ryee0701** [comment]
I found it..
https://github.com/TestableIO/System.IO.Abstractions/issues/761
so I add it to my csproj
```
<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
```
It work fine temporary..
keep dev...keep tracking..

**Comment by tg123** [comment]
`system io` will be removed from dependencies soon
