### ISSUE TITLE
Test certificates are not longer valid for MacOS and .NET Core 2.X

### ISSUE THREAD

**Issue by sesispla** [kubernetes-client/csharp#118]
I've found the following error executing the tests locally, with MacOS 10.12.6 (High Sierra) and latest .NET Core SDK (2.1.300-preview1-008174):

```
Failed   k8s.Tests.AuthTests.Cert
Error Message:
 Interop+AppleCrypto+AppleCommonCryptoCryptographicException : MAC verification failed during PKCS12 import (wrong password?)
Stack Trace:
   at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at k8s.Tests.AuthTests.Cert() in /Users/Sergio/Repositories/kubernetes/kubernetes-client-csharp/tests/AuthTests.cs:line 171
```

Accordingly to @qmfrederik in [corefx/24225](https://github.com/dotnet/corefx/issues/24225) _"If you have a PKCS#12 file which is not protected with a password, and which does have a MAC entry, opening the file will work on Windows and Linux but fails on Mac (which use CommonCrypto)."_

Maybe our test certificates can be regenerated with password protection.

**Comment by tg123** [comment]
I do not have a mac, cloud you please test if code below works?

CertUtils.cs:92

```
                const string password = "k8s";
                store.Save(pkcs, password.ToCharArray(), new SecureRandom());
                return new X509Certificate2(pkcs.ToArray(), password);
```

**Comment by sesispla** [comment]
Cool, we're almost there. Only one test failing now:

```
Failed   k8s.Tests.AuthTests.Cert
Error Message:
 Interop+AppleCrypto+AppleCommonCryptoCryptographicException : MAC verification failed during PKCS12 import (wrong password?)
Stack Trace:
   at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at k8s.Tests.AuthTests.Cert() in /Users/Sergio/Repositories/kubernetes/kubernetes-client-csharp/tests/AuthTests.cs:line 171

Total tests: 58. Passed: 57. Failed: 1. Skipped: 0.
```

**Comment by tg123** [comment]
cloud you please cherry-pick #119 again and test
It seems only the testcase problem, I added empty password to it and revert change from hardcode password `k8s`

**Comment by sesispla** [comment]
cherry-picked #119 (c489e06) and the remaining error persists:

```
Failed   k8s.Tests.AuthTests.Cert
Error Message:
 Interop+AppleCrypto+AppleCommonCryptoCryptographicException : MAC verification failed during PKCS12 import (wrong password?)
Stack Trace:
   at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password)
   at k8s.Tests.AuthTests.Cert() in /Users/Sergio/Repositories/kubernetes/kubernetes-client-csharp/tests/AuthTests.cs:line 171
[xUnit.net 00:00:18.1085190]   Finished:    tests

Total tests: 58. Passed: 57. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 21.7427 Seconds
```

**Comment by qmfrederik** [comment]
@sesispla Can you try #129? You may need to `export COMPlus_UseManagedHttpClientHandler=true` for this to work - see #129 for the details.

**Comment by sesispla** [comment]
Worked like a charm! Thx @qmfrederik
