### ISSUE TITLE
Yaml Deserialization Fails for k8s.Models.ResourceQuantity

### ISSUE THREAD

**Issue by RohanNagar** [kubernetes-client/csharp#136]
If I have this `deployment.yaml` file:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "3G"
          requests:
            memory: "3G"
```

The `resources` section causes problems in the YAML deserialization:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ((Line: 24, Col: 21, Idx: 423) - (Line: 24, Col: 25, Idx: 427): Exception during deserialization)
---> YamlDotNet.Core.YamlException: (Line: 24, Col: 21, Idx: 423) - (Line: 24, Col: 25, Idx: 427): Exception during deserialization
---> System.InvalidCastException: Invalid cast from 'System.String' to 'k8s.Models.ResourceQuantity'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
```

The interesting part is `Invalid cast from 'System.String' to 'k8s.Models.ResourceQuantity'`.

Here is my code:

```c#
Appsv1beta1Deployment deployment = Yaml.LoadFromFileAsync<Appsv1beta1Deployment>(filename).Result;

client.CreateNamespacedDeployment1(deployment, namedspace);
```

Am I doing something wrong? The same code works for the YAML when the `resources` section is left out.

**Comment by tg123** [comment]
see #126 
please try latest version

**Comment by RohanNagar** [comment]
@tg123 thanks, that looks like the right fix. Unfortunately there hasn't been a release with those changes yet.

@brendanburns when is the next release planned for?

**Comment by tyrannosaurusflex** [comment]
Same here, had the exact same problem, glad to see it's already pushed.
+1 for next release, I'm using the nuget package at the moment, which is quite old

**Comment by brendandburns** [comment]
0.7.0-beta posted:

https://www.nuget.org/packages/KubernetesClient/0.7.0-beta#

closing this issue.

**Comment by dk-do** [comment]
Hello everybody,
even if this issue is 4 years old, Iam currently facing the same problem in K8S Client Version 8.0.12. @brendandburns Any hints what is going wrong?

My code is:

```
var file = File.ReadAllText(@"c:\data\statefulset.yaml");
var deserializer = new YamlDotNet.Serialization.DeserializerBuilder().WithNamingConvention(CamelCaseNamingConvention.Instance).IgnoreUnmatchedProperties().Build();
V1StatefulSet statefulSet = deserializer.Deserialize<V1StatefulSet>(file);
```

**Comment by tg123** [comment]
did you test with KubernetesYaml?

**Comment by dk-do** [comment]
Thank you! That was my fault!
