### ISSUE TITLE
UnprocessableEntity with `CreateNamespacedJob`

### ISSUE THREAD

**Issue by samuela** [kubernetes-client/csharp#207]
I have a bit of code that's producing an UnprocessableEntity error no matter how simple I make it:

```f#
open k8s

let seqToIList lst = Array.ofSeq lst :> System.Collections.Generic.IList<_>

[<EntryPoint>]
let main argv =
  let config = KubernetesClientConfiguration(Host="http://localhost:8001")
  use client = new Kubernetes(config)

  let job =
    client.CreateNamespacedJob(
      body=Models.V1Job(
        apiVersion="batch/v1",
        metadata=Models.V1ObjectMeta(name="foo"),
        spec=Models.V1JobSpec(
          template=Models.V1PodTemplateSpec(
            Spec=Models.V1PodSpec(containers=seqToIList [
              Models.V1Container(name="bar", image="busybox")
            ])
          )
        )
      ),
      namespaceParameter="default"
    )

  0 // return an integer exit code
```

I'm running a GKE cluster through `kubectl proxy` on my local machine. I've verified that I can run other operations with the client. There is no pre-existing job named "foo". Here's the complete output:

```
cloudbuild [master !?*] -> dotnet run

Unhandled Exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'UnprocessableEntity'
   at k8s.Kubernetes.CreateNamespacedJobWithHttpMessagesAsync(V1Job body, String namespaceParameter, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedJobAsync(IKubernetes operations, V1Job body, String namespaceParameter, String pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedJob(IKubernetes operations, V1Job body, String namespaceParameter, String pretty)
   at Kumo.CloudBuild.main(String[] argv) in /Users/skainswo/dev/kumo/new-world/src/cloudbuild/Program.fs:line 84
```

What about this request is unprocessable? More broadly, this error message is far from illuminating. It would be great if the API could either return more descriptive information and have this relayed to the user or have the client prevent sending malformed API requests.

**Comment by samuela** [comment]
Also: abstracting out the `Models.V1Job(...)` definition and calling `.Validate()` on it does not produce any errors.

**Comment by samuela** [comment]
Is there any way of taking a request like this and producing the corresponding JSON or YAML file? I'd be curious to try out the same request via kubectl.

**Comment by samuela** [comment]
I'm afraid that's the complete output, so I don't think there's an InnerException.

I ran `kubectl --v=40000 proxy` for a bit more information. That produced something like
```
kumo-cloudbuilder [master !?*] -> kubectl --v=40000 proxy
I1012 23:16:28.023308   30622 loader.go:357] Config loaded from file /Users/skainswo/.kube/config
Starting to serve on 127.0.0.1:8001
I1012 23:16:35.059284   30622 proxy_server.go:98] /apis/batch/v1/namespaces/default/jobs matched ^.*
I1012 23:16:35.059316   30622 proxy_server.go:98] localhost matched ^localhost$
I1012 23:16:35.059324   30622 proxy_server.go:138] Filter accepting POST /apis/batch/v1/namespaces/default/jobs localhost
I1012 23:16:35.059613   30622 upgradeaware.go:237] Request was not an upgrade
I1012 23:16:35.060224   30622 round_trippers.go:387] curl -k -v -XPOST  -H "Content-Length: 311" -H "X-Forwarded-For: 127.0.0.1" -H "User-Agent: FxVersion/4.6.26919.02 k8s.Kubernetes/1.2.0.59098" -H "Content-Type: application/json; charset=utf-8" https://35.236.80.2/apis/batch/v1/namespaces/default/jobs?pretty=true
I1012 23:16:35.205254   30622 round_trippers.go:406] POST https://35.236.80.2/apis/batch/v1/namespaces/default/jobs?pretty=true 422 Unprocessable Entity in 144 milliseconds
I1012 23:16:35.205286   30622 round_trippers.go:412] Response Headers:
I1012 23:16:35.205298   30622 round_trippers.go:415]     Content-Type: application/json
I1012 23:16:35.205307   30622 round_trippers.go:415]     Content-Length: 595
I1012 23:16:35.205317   30622 round_trippers.go:415]     Date: Sat, 13 Oct 2018 06:16:37 GMT
I1012 23:16:35.205327   30622 round_trippers.go:415]     Audit-Id: 4e683a39-1785-4811-88e5-3e3a9343f258
```

Digging through the cluster audit logs for that Audit-Id led me to this gem:
```
Job.batch "foo" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"
```
Setting `restartPolicy` on `Models.V1PodSpec` got it all sorted out, so I'm onto new problems now.

**Comment by itowlson** [comment]
I reproduced this (thanks for the very clear sample!) and it looks like there is a way to get the server error info out of the exception object.  If the exception is a `Microsoft.Rest.HttpOperationException` (which it is in this case) then the exception contains a `Response` property.  `Response.Content` contains the body of the server error response.

Unfortunately, this stuff is generated by AutoRest, so it's not easy for us to surface this in the exception message - AutoRest doesn't provide this level of customisation (as far as I know), and to add it we would have to wrap all calls to the generated layer in an exception transformer.  I hope the `Response.Content` tip is enough to help you out in future - we should certainly document this more clearly!

I'm not sure why the `restartPolicy` is defaulting to `Always` if that is considered invalid by the server.  Possibly there is some versioning issue between the client and the server here, not sure, but looks like we should review our defaults.

Thanks for reporting this - sorry I can't promise anything more positive.

**Comment by samuela** [comment]
@itowlson Thanks for looking into this! It's very helpful to know that the exception contains the API response with some info. That sounds easier than digging through the audit logs.
