### ISSUE TITLE
Library can't load eliptic curve keys

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#242]
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'Org.BouncyCastle.Crypto.Parameters.ECPrivateKeyParameters' to type 'Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters'.
   at k8s.CertUtils.GeneratePfx(KubernetesClientConfiguration config)
   at k8s.Kubernetes.SetCredentials(KubernetesClientConfiguration config, HttpClientHandler handler)
   at eventrouter.EventRouter.Main(String[] args) in /crypthome/brendan/src/k8s-event-bridge/src/EventRouter.cs:line 17
```

**Comment by maximmasiutin** [comment]
There is a discussion on this topic at https://stackoverflow.com/questions/67995687/which-of-the-elliptic-curves-are-supported-for-the-kubernetes-certificates with solution proposed - not sure whether it is relevant. What do you think on that matter?
