### ISSUE TITLE
Client can't handle 201/Status responses...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#29]
The Kubernetes Swagger is incomplete, and the AutoRest code is very precise.  It's a bad combination.

Stack trace looks like:

```
Unhandled Exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Created'
   at k8s.Kubernetes.<CreateNamespaceWithHttpMessagesAsync>d__35.MoveNext() in /mnt/c/Users/bburns/kubernetes-client/csharp/src/generated/Kubernetes.cs:line 1927
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at k8s.KubernetesExtensions.<CreateNamespaceAsync>d__19.MoveNext() in /mnt/c/Users/bburns/kubernetes-client/csharp/src/generated/KubernetesExtensions.cs:line 624
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at k8s.KubernetesExtensions.CreateNamespace(IKubernetes operations, V1Namespace body, String pretty) in /mnt/c/Users/bburns/kubernetes-client/csharp/src/generated/KubernetesExtensions.cs:line 605
   at simple.PodList.Main(String[] args) in /mnt/c/Users/bburns/kubernetes-client/csharp/examples/simple/PodList.cs:line 26
```

**Comment by brendandburns** [comment]
I'm an idiot, this is a duplicate of #9...
