### ISSUE TITLE
TLS failure when running on Windows Server 2012 R2

### ISSUE THREAD

**Issue by xinyanmsft** [kubernetes-client/csharp#290]
Report from one of our customers. This happens on Windows Server 2012 R2. Code combined against .Net Framework 4.6.1

Invoking methods such as ReadNamespacedPod will result in HttpRequestException: 'An error occurred while sending the request.', with Inner exception 'WebException: The request was aborted: Could not create SSL/TLS secure channel.'

**Comment by alecor191** [comment]
I'm seeing the same error in the following setup:

- Windows 10, build 1903
- Docker for Windows with Kubernetes enabled (Linux containers)
- Calling `ListNamespacedPodAsync()` fails with the same error as mentioned above when executed from within the pod:

```csharp
var configuration = KubernetesClientConfiguration.InClusterConfig();
var client = new Kubernetes(configuration);

// The following line throws the exception when executed from a service hosted inside the cluster
var pods = await client.ListNamespacedPodAsync("default", labelSelector: "app=<myapp>");
```

Note that executing the following code from an app executed on the same machine, but outside the cluster, works fine:

```csharp
var configuration = KubernetesClientConfiguration.BuildDefaultConfig(); // Load default config
var client = new Kubernetes(configuration);

// The following line works when executed from a process on the host machine.
var pods = await client.ListNamespacedPodAsync("default", labelSelector: "app=<myapp>");
```

**Comment by pawelpabich** [comment]
Same here. It works on Windows 10 but fails on Windows 2012 R2. The app is .NET Core 2.2. 
Any idea what that might be?

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ReplaceNamespacedIngressWithHttpMessagesAsync(Extensionsv1beta1Ingress body, String name, String namespaceParameter, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReplaceNamespacedIngressAsync(IKubernetes operations, Extensionsv1beta1Ingress body, String name, String namespaceParameter, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReplaceNamespacedIngress(IKubernetes operations, Extensionsv1beta1Ingress body, String name, String namespaceParameter, String dryRun, String fieldManager, String pretty)
   at 
```

**Comment by pawelpabich** [comment]
It looks like the set of ciphers that K8s API endpoint accepts is very limited: 

![image](https://user-images.githubusercontent.com/347637/65003351-8342c600-d93b-11e9-9f3f-5bc9c49dae9f.png)

**Comment by Jman012** [comment]
I am experiencing the exact same scenario.

Server:
- TLS 1.2 only
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
- https://www.ssllabs.com/ssltest/analyze.html?d=api.uat.equifax.com

Clients:
- Windows 10 1903, .NET Core 2.2 (works)
  - Has all four cipher suites
- Windows Server 2012 R2, .NET Core 2.2 (does not work)
  - Has only the DHE cipher suites

Exception on Windows Server 2012 R2:
`System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted`

**Comment by Jman012** [comment]
I resolved this by toggling some of the Windows Server security settings for ciphers on and then off, and then restarting the server. The image that the server was based off of likely had wrong defaults.

**Comment by alecor191** [comment]
@Jman012 were you able to identify what security settings were required to get this working?
