### ISSUE TITLE
AKS: Config made with KubernetesClientConfiguration.InClusterConfig() authenticates but is Forbidden

### ISSUE THREAD

**Issue by raylinz1** [kubernetes-client/csharp#315]
Wrote a quick app that tracks the stability of pods being created and destroyed in our AKS environments. When my .kube/config is set to my AKS instance and I run on my local machine with the client config built from KubernetesClientConfiguration.BuildConfigFromConfigFile(); everything runs great. When I publich my container to the ACR and deploy to my pod, the client config built from KubernetesClientConfiguration.InClusterConfig(); authenticates to the cluster but is forbidden from making cluster-api calls resulting in the following error when executing Pods = _client.ListPodForAllNamespaces();

Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
         at k8s.Kubernetes.ListPodForAllNamespacesWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String pretty, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
         at k8s.KubernetesExtensions.ListPodForAllNamespacesAsync(IKubernetes operations, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String pretty, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, CancellationToken cancellationToken)

I'm sure this is probably not a bug but if there is insight as to how I might fix this error in AKS pods, that would help. Do I have to set something in my deployment.yml for the pod or update some field in my compiled container possibly?

Thanks,
Ray

**Comment by brendandburns** [comment]
By default the `InClusterConfig()` uses the default `serviceaccount` for the Pod. This error means that that service account doesn't have the right RBAC.

For more details on service accounts and RBAC, please see this section:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

and this on RBAC:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions

**Comment by raylinz1** [comment]
Thanks Brendan! I was able to find that I needed a clusterRoleBinding to resolve my issue.

Much appreciated.

Snippet for resolution from RBAC service account permissions that resolved my issue:

kubectl create clusterrolebinding add-on-cluster-admin \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:default
