### ISSUE TITLE
How to add proxy credentials

### ISSUE THREAD

**Issue by DotNetRockStar** [kubernetes-client/csharp#355]
I am having an issue right now where the client is attempting to make a request to the k8s cluster and fails due to proxy authentication issues.  How can I go about adding proxy credentials into the client so that the calls to k8s api do not fail.

```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'ProxyAuthenticationRequired'
at k8s.Kubernetes.ListNamespacedDeploymentWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedDeploymentAsync(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, CancellationToken cancellationToken)
```

Thanks in advance.

**Comment by brendandburns** [comment]
You can pass an `HttpClientHandler` into the Client constructor which has the `HttpClientHandler.DefaultProxyCredentials` set properly.

You can use `KubernetesClientConfiguration.CreateDefaultHttpHandler()` (https://github.com/kubernetes-client/csharp/blob/3a30033090e6866a4050b4cc68cebd2ee228bb12/src/KubernetesClient/KubernetesClientConfiguration.HttpClientHandler.cs#L7) to create a starting point for the `HttpClientHandler`

**Comment by DotNetRockStar** [comment]
This is perfect. Thank you!

**Comment by brendandburns** [comment]
Closing this issue, since I think the question is answered. Please use the `/reopen` command to reopen if necessary.
