### ISSUE TITLE
Watcher breaks after getting an event for an object with failure condition

### ISSUE THREAD

**Issue by mitsuthar** [kubernetes-client/csharp#363]
Here is how I am creating my watcher.

`var watcher = await kubernetesClient.ListNamespacedJobWithHttpMessagesAsync(
namespaceParameter: "mynamespace",
watch: true,
labelSelector: "label=value");`

`using (watcher.Watch<V1Job, V1JobList>(
onEvent: async (watchEventType, job) => await OnEvent(job),
onError: ex => OnError(ex, waitTokenSource),
onClosed: () => OnClosed(waitTokenSource)))`
`{ await Task.Delay(Timeout.Infinite, waitToken); }`

Watcher throws exception when there is an event for a job with failure condition. 
`The response ended prematurely.
   at System.Net.Http.HttpConnection.Fill()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.ReadLine()
   at System.IO.TextReader.<>c.<ReadLineAsync>b__13_0(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListNamespacedJobWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)`

The watcher keeps breaking until I remove the job with the failure condition from the cluster.

**Comment by brendandburns** [comment]
My guess is that this is a parse error of some sort. If you do a `GET` for the same failed job does it work? My bet is that it won't.

I'll take a look at the code and see if we should be handling the parse error better.

**Comment by mitsuthar** [comment]
Hi @brendanburns thanks for the response.

"ListNamespacedJobAsync" works and I get all the jobs correctly
also 
kubectl get jobs -n namespace --watch works fine.

For some reasons 'ListNamespacedJobWithHttpMessagesAsync' is taking more than 30 seconds to execute with only 3-4 jobs in the GKE cluster. Not sure if this is related.

**Comment by tg123** [comment]
hi 
is `ListNamespacedJobAsync` slow too?

**Comment by mitsuthar** [comment]
@tg123 ListNamespacedJobAsync is working fine. It takes ~1-2 seconds consistently.

**Comment by mitsuthar** [comment]
I have some new information which could help with this issue.
When I ran 'kubectl proxy' locally and change the config to use the host on localhost, I got descriptive error.
- Newtonsoft failed at object.spec.template.spec.volume[2] for a missing '/'. (I did not copy the exact error and can not reproduce the issue at the moment).
- The volume has definition like below.
- name: mount-122
        nfs:
          path: /folder1/folder2
          server: IP Address

Once I deleted that one job, the error went away and 'ListNamespacedJobWithHttpMessagesAsync' became fast (1 second instead of 30 seconds).

The error is a bit difficult reproduce, but happens every now and then breaks the service built on it.

**Comment by mitsuthar** [comment]
I reproduced the error with kube api (without this client library). So I think this is not an issue with this library.
`curl http://localhost:8001/apis/batch/v1/namespaces/dev/jobs\?labelSelector\=Environment\=Development\&watch\=true`
When running this command I received a broken json response and the connection crashed.

Broken response
`{"type":"ADDED","object":{"kind":"Job","apiVersion":"batch/v1","metadata":{"name":"18-gapfilledforecastdataprep","namespace":"dev-vn50j2y","selfLink":"/apis/batch/v1/namespaces/dev-vn50j2y/jobs/18-gapfilledforecastdataprep","uid":"0c358d32-161b-4c86-b16d-ee2e7f60de72","resourceVersion":"1133388","creationTimestamp":"2020-03-09T17:19:29Z","labels":{"Environment":"Development","ExternalId":"18","Id":"42","RelayId":"OBFUSCATE","ScenarioId":"OBFUSCATE"}},"spec":{"parallelism":1,"completions":1,"backoffLimit":3,"selector":{"matchLabels":{"controller-uid":"OBFUSCATE"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"controller-uid":"OBFUSCATE","job-name":"some-job"}},"spec":{"volumes":[{"name":"mount-124","nfs":{"server":"OBFUSCATE,"path":"OBFUSCATE"}},{"name":"mount-123","nfs":{"server":"OBFUSCATE","path":"OBFUSCATE"}},{"name":"mount-122","nfs":{"server":"OBFUSCATE","path":"OBFUSCATE"}}],"containers":[{"%`

**Comment by mitsuthar** [comment]
So I have figured out the problem.
The problem was the reverse proxy I had in-front of kube api.
I needed to add "proxy_buffering off;" in my nginx reverse proxy configuration.
Thanks @tg123 @brendandburns for your time.
