### ISSUE TITLE
KubernetesClient authentication doesn't work when routed through PS Remoting.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#460]
This fails:
```
PS D:\> Invoke-Command -ScriptBlock {Import-Module C:\hcs\KubernetesClient.dll;$config = [k8s.KubernetesClientConfiguration]::BuildConfigFromConfigFile("some\file");$cl = [k8s.Kubernetes]::new($config);$cl.ListAPIService1WithHttpMessagesAsync(); echo "Success"} -ComputerName $ip -Credential $cred

PSComputerName         : $ip
RunspaceId             : 
Id                     : 55
Exception              : System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while
                         sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
                            at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                            at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                            --- End of inner exception stack trace ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at k8s.WatcherDelegatingHandler.<SendAsync>d__0.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at k8s.Kubernetes.<ListAPIService1WithHttpMessagesAsync>d__264.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. --->
                         System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
                            at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                            at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
                            --- End of inner exception stack trace ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at k8s.WatcherDelegatingHandler.<SendAsync>d__0.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at k8s.Kubernetes.<ListAPIService1WithHttpMessagesAsync>d__264.MoveNext()<---
 
Status                 : Faulted
IsCanceled             : False
IsCompleted            : True
CreationOptions        : None
AsyncState             :
IsFaulted              : True
AsyncWaitHandle        : System.Threading.ManualResetEvent
CompletedSynchronously : False
```

Local Invocation directly on $ip machine succeeds  --

 
```
PS C:\Users\EdgeLabUser> Import-Module C:\hcs\KubernetesClient.dll;$config = [k8s.KubernetesClientConfiguration]::BuildConfigFromConfigFile("some\file");$cl = [k8s.Kubernetes]::new($config);$cl.ListAPIService1WithHttpMessagesAsync();

Result                 : Microsoft.Rest.HttpOperationResponse`1[k8s.Models.V1beta1APIServiceList]
Id                     : 90
Exception              :
Status                 : RanToCompletion
IsCanceled             : False
IsCompleted            : True
CreationOptions        : None
AsyncState             :
IsFaulted              : False
AsyncWaitHandle        : System.Threading.ManualResetEvent
CompletedSynchronously : False
```

**Comment by brendandburns** [comment]
Debugging indicates this may have something to do with the way that network credentials work and enabling interactive session via `Enable-WSManCredSSP ` fixes things.
