### ISSUE TITLE
Watch crashes when watching empty lists - Possible regression

### ISSUE THREAD

**Issue by winromulus** [kubernetes-client/csharp#494]
Hi,

Listing any resource and attaching a watcher results in an exception.

To reproduce easily, run the following on a cluster without CRDs installed:
```
var watcher = await client.ListCustomResourceDefinitionWithHttpMessagesAsync(watch: true);

```
Results in:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListCustomResourceDefinitionWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
```

This seems like a regression because I remember this not being a problem in previous versions of the client (I think in 1.16.x it was working).

This was tested using KubernetesClient version 2.0.x (including 2.0.33) on all Kubernetes versions starting with 1.15.x up to 1.19.2

**Comment by sebagomez** [comment]
Same thing is happening to me when waiting for certain `CRD` that is not in the cluster.

```cs
listResponse = await Kubernetes.ListNamespacedCustomObjectWithHttpMessagesAsync(m_crd.Group, m_crd.Version, k8sNamespace, m_crd.Plural, watch: true);
```

The internal most exception I get is a `SockerException` (ErrorCode: 89).  
The exception is originally fired from the `Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)` in the `WatcherDelegatingHandler.cs` file when reading async from the inner stream:

```cs
return await _innerStream.ReadAsync(buffer, offset, count, cancellationTokenSource.Token)
```

![image](https://user-images.githubusercontent.com/1637983/95368371-68c3ed80-08ac-11eb-9af6-c853ba358dda.png)

**Comment by tg123** [comment]
may i know your runtime?
e.g. netcore31?

**Comment by sebagomez** [comment]
```
❯ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by roblapp** [comment]
I am running into this as well using the latest code from master. I am running through the examples and I am simply trying to watch jobs in a given namespace with Kubernetes on Docker desktop.

Here is the invocation that is failing:
```
var jobList = await client.ListNamespacedJobWithHttpMessagesAsync(
                        "default",
                        watch: true);
```
Stack trace:
```
An Exception was thrown: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.
 ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request   
   --- End of inner exception stack trace --- 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error) 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) 
   at System.Net.Http.HttpConnection.FillAsync() 
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)   
   --- End of inner exception stack trace --- 
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken) 
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\Code\3rd Party Libs\csharp\src\KubernetesClient\WatcherDelegatingHandler.cs:line 66 
   at System.IO.StreamReader.ReadBufferAsync() 
   at System.IO.StreamReader.ReadLineAsyncInternal() 
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync() in C:\Code\3rd Party Libs\csharp\src\KubernetesClient\WatcherDelegatingHandler.cs:line 204 
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in C:\Code\3rd Party Libs\csharp\src\KubernetesClient\WatcherDelegatingHandler.cs:line 164 
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) 
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) 
   at k8s.Kubernetes.ListNamespacedJobWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken) in C:\Code\3rd Party Libs\csharp\src\KubernetesClient\generated\Kubernetes.cs:line 86422 
   at watch.Program.WatchOriginal(IKubernetes client) in C:\Code\3rd Party Libs\csharp\examples\watch\Program.cs:line
``` 
Here is my OS/dotnet info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by brendandburns** [comment]
I can't reproduce this on my machine.

Note that you don't need the `await` when watching, so perhaps try removing the `await` call and see if it fixes things?

If it doesn't, can you include the complete sample code for a reproduction?

**Comment by sebagomez** [comment]
I will try your suggestion and if it still happens I'll create a small repro project for you to test.

**Comment by roblapp** [comment]
So I noticed two things:

1) When `watch` is set to false and I await the `ListNamespacedJobWithHttpMessagesAsync` no Exception is thrown and I get the results as expected.

2) If I want to setup a watch and I don't await the `ListNamespacedJobWithHttpMessagesAsync` invocation and `watch` is set to true it **does** throw the `Exception` I added above (at least that's the behavior I am seeing). This is with the latest code from master as of 10/30/2020 @ 16:42 UTC. Make sure you

```
namespace TestApp
{
    public class Program
    {
          public static async Task Main(string[] args)
          {
                var config = KubernetesClientConfiguration.BuildConfigFromConfigFile();
                var client = new Kubernetes(config);

                var jobList = client.ListNamespacedJobWithHttpMessagesAsync(
                    "Some Namespace That Does Not Have Any Jobs",
                     watch: true);

                 using (jobList.Watch<V1Job, V1JobList>(
                         (type, item) =>
                         {
                               Console.WriteLine("== STARTING WATCH EVENT ==");
                               Console.WriteLine("Event type {0} on job {1} with resource version {2}", type, item.Metadata.Name, item.Metadata.ResourceVersion);
                               Console.WriteLine("== COMPLETED WATCH EVENT ==\n\n");
                         },
                        exception =>
                        {
                              Console.WriteLine("Exception occurred on watch: {0}", exception);
                        },
                        () =>
                        {
                              Console.WriteLine("Connection has closed");
                        }))
                            {
                               Console.WriteLine("press ctrl + c to stop watching");
                               var ctrlc = new ManualResetEventSlim(false);
                               Console.CancelKeyPress += (sender, eventArgs) => ctrlc.Set();
                               ctrlc.Wait();
                               Console.WriteLine("Done");
                          }
        }
    }
}
```

**Comment by sebagomez** [comment]
> 
> Note that you don't need the `await` when watching, so perhaps try removing the `await` call and see if it fixes things?
> 
For what I see, if I remove the await I don't get the mentioned Exception. The thing is, now my code keeps iterating... maybe I'm using it wrong. I want to wait for a specific object whose CRD might not be created yet... I can also create a small repro if it helps. But I feel I might not be using the right pattern with the `ListNamespacedCustomObjectWithHttpMessagesAsync` and  `Watch`.

**Comment by winromulus** [comment]
@brendanburns, @sebagomez 
Removing the `await` does nothing but defer the exception.
See output below:
```
press ctrl + c to stop watching
Exception occurred on watch: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListJobForAllNamespacesWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.WatcherExt.<>c__DisplayClass0_0`2.<<Watch>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
Connection has closed
```

**Comment by roblapp** [comment]
Yeah the Exception occurs after a few minutes. Let the app run for at least 10 minutes and I am pretty confident you will see it.

**Comment by winromulus** [comment]
@roblapp - same amount of time it took with the `await` to throw the Exception. The only difference is that you don't get to the `.Watch` with the await.

**Comment by sebagomez** [comment]
Yeah, sorry... it does happen later on

**Comment by roblapp** [comment]
Any update on this?

**Comment by brendandburns** [comment]
I still can reproduce this in my local setup.

Note that a watch is a hanging TCP connection. Depending on your network setup, with no traffic, the TCP connection can get severed/terminated by network hardware due to timeouts.

You shouldn't expect that a watch will exist forever, you definitely need to be doing list/watch in a loop.
