### ISSUE TITLE
Error when trying to fetch Kubernetes Object within a watch loop.

### ISSUE THREAD

**Issue by cwoolum** [kubernetes-client/csharp#499]
I am trying to create a Kubernetes Controller in C# and am having a bit of trouble with making a request. My basic flow is as follows:

1. Watch for CRD's 
2. When CRD is added, check to see if a matching deployment for that resource exists.
3. If not, create it. Otherwise, make sure all parameters match.

I have a watcher set up and that seems to work fine but if I try to make a call to get the deployment, I get an error.

``` csharp
var client = new Kubernetes(kubeConfig);
var result = await client.ListNamespacedCustomObjectWithHttpMessagesAsync(
                    group: _crd.ApiVersion.Split('/')[0],
                    version: _crd.ApiVersion.Split('/')[1],
                    namespaceParameter: _crd.Namespace,
                    plural: _crd.PluralName,
                    watch: true,
                    timeoutSeconds: (int)TimeSpan.FromMinutes(60).TotalSeconds)
                    .ConfigureAwait(false);

while (!token.IsCancellationRequested)
{
  result.Watch<T, object>(async (type, item) =>{

   var deployment = await client.ReadNamespacedDeploymentAsync(example.Metadata.Name, example.Metadata.NamespaceProperty);
   
  if (deployment == null)
  {
    await CreateDeploymentIfNotExists(example, client, example.Metadata.NamespaceProperty);
   }
  }, (ex) =>
  {
     _logger.LogError(ex, "An error occurred fetching the custom object.");
  });
}
```

The error I get is :
```
[12:20:17 ERR] An error occurred fetching the custom object.
System.NotSupportedException:  The ReadAsync method cannot be called when another read operation is pending.
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
```

I tried creating a separate client for inside the handler but the error is the same. What am I missing here?

**Comment by brendandburns** [comment]
Yep, that's the right way to do it
