### ISSUE TITLE
User: user@domain.com does not have appropriate auth credentials in kubeconfig

### ISSUE THREAD

**Issue by daniv-msft** [kubernetes-client/csharp#524]
Hello,

I'm working on the [Bridge to Kubernetes](https://github.com/Microsoft/mindaro) product, and one of our customers reported an exception recently that seems to be coming from the C# KubernetesClient:
```
k8s.Exceptions.KubeConfigException: {
	"StackTrace":"
		at k8s.KubernetesClientConfiguration.SetUserDetails(K8SConfiguration k8SConfig, Context activeContext)
		at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
		at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
		at k8s.KubernetesClientConfiguration.BuildConfigFromConfigObject(K8SConfiguration k8SConfig, String currentContext, String masterUrl)
		at Microsoft.DevSpaces.Common.Kubernetes.K8sClientFactory.CreateFromKubeConfig(K8SConfiguration kubeConfig)",
	"Message":"User: user@domain.com does not have appropriate auth credentials in kubeconfig",
}
```

The customer is using an OIDC authprovider ([keycloak](https://www.keycloak.org/)).
The kubeconfig used seems to be valid. Please note that the PII data has been removed (same thing above in the exception):
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <certificate-authority-data>
    server: https://api.test.<cluster-domain>
  name: test.<cluster-domain>
contexts:
    cluster: test.<cluster-domain>
    namespace: <namespace>
    user: <user@domain.com>
  name: test.<cluster-domain>
current-context: test.<cluster-domain>
kind: Config
preferences: {}
users:
- name: <user@domain.com>
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: ""
        id-token: <id-token>
        idp-issuer-url: https://<auth-domain>/auth/realms/master
        refresh-token: <refresh-token>
      name: oidc
```
Also, the user mentions that running `kubectl` commands work with this same kubeconfig.

Could you please let me know if you have an idea of what might cause this?

**Comment by tg123** [comment]
oidc is not supported at the moment :(

**Comment by daniv-msft** [comment]
All right, thanks @tg123 for your quick reply and clarifying this.
