### ISSUE TITLE
UnsupportedMediaType Exception with Patch Custom Object APIs

### ISSUE THREAD

**Issue by mocsharp** [kubernetes-client/csharp#558]
Getting the following error with `PatchNamespacedCustomObjectWithHttpMessagesAsync` and `PatchNamespacedCustomObjectAsync` after helm 2->3 upgrade. Any idea?

```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'UnsupportedMediaType'
   at k8s.Kubernetes.PatchNamespacedCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String name, String dryRun, String fieldManager, Nullable`1 force, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.PatchNamespacedCustomObjectAsync(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String name, String dryRun, String fieldManager, Nullable`1 force, CancellationToken cancellationToken)
   at Repositories.KubernetesClientWrapper.PatchNamespacedCustomObjectWithHttpMessagesAsync[T](CustomResourceDefinition crd, T item, String name)
   at Services.Jobs.InferenceRequestStore.<>c__DisplayClass26_0.<<UpdateInferenceRequest>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
```

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml","reason":"UnsupportedMediaType","code":415}
```

**Comment by tg123** [comment]
may i know the server version and c# sdk version?
seems we fixed it already

**Comment by mocsharp** [comment]
Server 1.19.7
SDK: 4.0.5

**Comment by tg123** [comment]
could you please share the code how do you `patch`?
