### ISSUE TITLE
Does API support global http_proxy setting on linux?

### ISSUE THREAD

**Issue by YurongHe** [kubernetes-client/csharp#568]
Our product is running on Linux Kubernetes, in the controller code, we are using this client api to get ns and crds.

When using .netcore container, with http_proxy global setting in the container, got the following exception.

2021-02-19 22:03:29.9823 | INFO  | WARN: Commandline parameters are currently not support. Ignoring the following args: --verbosity detailed
2021-02-19 22:05:10.4761 | ERROR | An unexpected failure occurred while starting or running the controller service. k8s.KubernetesException: <ListConfigMap>b__0 was cancelled: The operation was canceled.
---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListNamespacedConfigMapWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedConfigMapAsync(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedConfigMap(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty)

My question is:
in order to use http proxy, how do we config this for .netcore code?

**Comment by tg123** [comment]
http proxy is .net runtime level 
looks like your proxy timeout

**Comment by YurongHe** [comment]
> http proxy is .net runtime level
> looks like your proxy timeout

do you mean k8s client code should handle this correctly? if so, i have no_proxy=localhost,127.0.0.1,100.64.0.0/16,10.96.0.0/12, kubernetes.default.svc. I also added machine ip to no_proxy.

I don't know if anything else should be in no_proxy to make it k8s client api work.

**Comment by tg123** [comment]
yes 
the underlayer socket should apply your environment variables

the exception you pasted is something like connection timeout after proxy env added. please check you proxy

**Comment by YurongHe** [comment]
Suppose all kubernetes client calls are internal and shouldn't go to proxy server. Not sure why it is timeout. Is it possible the API didn't take no_proxy setting? Or no_proxy is not setup correctly?

Could you confirm API could take no_proxy settings? So we can figure out the proper values for no_proxy.

**Comment by nwoodmsft** [comment]
I have similar questions about NO_PROXY - is CIDR notation being honored by the .net runtime / libs used by this project? We typically exempt a bunch of CIDR ranges in our NO_PROXY value to exempt k8s API server ip addresses and private ip space etc from the proxy....but the behavior I am seeing makes it look like
