### ISSUE TITLE
Connect issue:  Sockets on this platform are invalid for use after a failed connection attempt

### ISSUE THREAD

**Issue by dannystommen** [kubernetes-client/csharp#587]
When running a random command again the 4.19 SDK, we receive  the error:  Sockets on this platform are invalid for use after a failed connection attempt

`System.Net.Http.HttpRequestException : Sockets on this platform are invalid for use after a failed connection attempt. (5b0fdf959f2e105c6a9b130acf348694.yl4.eu-west-1.eks.amazonaws.com:443)
---- System.PlatformNotSupportedException : Sockets on this platform are invalid for use after a failed connection attempt.
  Stack Trace:
     at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at k8s.Kubernetes.ListNamespacedJobWithHttpMessagesAsync(String namespaceParameter, Nullable 1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable 1 limit, String resourceVersion, String resourceVersionMatch, Nullable 1 timeoutSeconds, Nullable 1 watch, String pretty, Dictionary 2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedJobAsync(IKubernetes operations, String namespaceParameter, Nullable 1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable 1 limit, String resourceVersion, String resourceVersionMatch, Nullable 1 timeoutSeconds, Nullable 1 watch, String pretty, CancellationToken cancellationToken)`
   
 This is being executed towards AWS EKS, running version 1.18.

On my local Windows machine it's working fine. When running this on the EKS cluster (linux), it fails with the above mentioned error. In the 4.16 SDK this does work.

**Comment by rodrigoreis** [comment]
I had this problem in version 4.0.19, downgraded to version 4.0.16 it worked ok.

**Comment by brendandburns** [comment]
I'm pretty sure this is caused by this change:

https://github.com/kubernetes-client/csharp/pull/560

**Comment by brendandburns** [comment]
More details
https://github.com/dotnet/runtime/issues/24917

**Comment by brendandburns** [comment]
#588 fixed this issue.

**Comment by dannystommen** [comment]
Awesome, thanks!
