### ISSUE TITLE
SslCaCerts appears to be require even though kubectl does not need it

### ISSUE THREAD

**Issue by lucastheisen** [kubernetes-client/csharp#621]
If i understand correctly (from other comments I think i have seen on this project), if it works in `kubectl` it should work here.  However, my KUBECONFIG does not have an explicit `certificate-authority` nor `certificate-authority-data` and `kubectl` commands still work fine.  However, when i use this library i still get:

```console
Unhandled exception. k8s.Exceptions.KubeConfigException: A CA must be set when SkipTlsVerify === false
   at k8s.Kubernetes.InitializeFromConfig(KubernetesClientConfiguration config)
   at k8s.Kubernetes.CreateHttpClient(DelegatingHandler[] handlers, KubernetesClientConfiguration config)
   at k8s.Kubernetes..ctor(KubernetesClientConfiguration config, DelegatingHandler[] handlers)
   at k8s.GenericClient..ctor(KubernetesClientConfiguration config, String group, String version, String plural)
```

This appears to be part of the [configuration initialization](https://github.com/kubernetes-client/csharp/blob/09f08d76590b3da06ea29beaa053f3b95564a380/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L293-L306):

```csharp
            if (uri.Scheme == "https")
            {
                if (!string.IsNullOrEmpty(clusterDetails.ClusterEndpoint.CertificateAuthorityData))
                {
                    var data = clusterDetails.ClusterEndpoint.CertificateAuthorityData;
                    SslCaCerts = new X509Certificate2Collection(new X509Certificate2(Convert.FromBase64String(data)));
                }
                else if (!string.IsNullOrEmpty(clusterDetails.ClusterEndpoint.CertificateAuthority))
                {
                    SslCaCerts = new X509Certificate2Collection(new X509Certificate2(GetFullPath(
                        k8SConfig,
                        clusterDetails.ClusterEndpoint.CertificateAuthority)));
                }
            }
```

It seems like there should be an allowed _else_ condition that falls back to the OS level CA.  I can work around this with something like:

```csharp
            var k8sConfig = KubernetesClientConfiguration
                    .BuildConfigFromConfigFile(this.configuration.KubeConfigFile);

            // point to OS level ca-certificates file
            k8sConfig.SslCaCerts = new X509Certificate2Collection(
                new X509Certificate2("/etc/ssl/certs/ca-certificates.crt"));

            var client = new Kubernetes(k8sConfig);
```

But it seems like this should not be necessary if `kubectl` doesn't need it.

If this is desired, is there some documentation I missed?

**Comment by lucastheisen** [comment]
It seems like `X509Store` could be used when neither `CertificateAuthority` nor `CertificateAuthorityData` is present.  This works for me (both Windows and Ubuntu 18 via WSL):

```csharp
            var myNamespace = "default";
            using var store = new X509Store(
                StoreName.CertificateAuthority,
                StoreLocation.CurrentUser,
                OpenFlags.ReadOnly);

            var k8sConfig = KubernetesClientConfiguration.BuildDefaultConfig();
            k8sConfig.SslCaCerts = store.Certificates;

            using var client = new Kubernetes(k8sConfig);
            var pods = client.ListNamespacedPod(myNamespace);
            foreach (var pod in pods.Items)
            {
                Console.WriteLine($"Pod: {pod.Metadata.Name}");
            }
```

But it definitely seems like this should be in the core `KubernetesClientConfiguration.SetClusterDetails`. I'd put in a PR if I could figure out what is generated vs what is not.

**Comment by tg123** [comment]
cert store is specific to windows, as a result the client sdk does not support it

**Comment by lucastheisen** [comment]
@tg123 , that was tested on Ubuntu and CentOS 7 and both worked.  It may have initially been a windows only feature, but it appears to have been ported. This is my exact program:

```csharp
﻿namespace InvestigateX509
{
    using System;
    using System.Security.Cryptography.X509Certificates;
    using k8s;

    class Program
    {
        private static void DumpStore(StoreName name, StoreLocation location)
        {
            using var store = new X509Store(name, location, OpenFlags.ReadOnly);
            Console.WriteLine($"\n\nBegin {store.Name} at {store.Location}");
            foreach (var cert in store.Certificates)
            {
                Console.WriteLine($"Cert is: {cert}");
            }
        }

        static void Main(string[] args)
        {
            DumpStore(StoreName.CertificateAuthority, StoreLocation.CurrentUser);
            DumpStore(StoreName.CertificateAuthority, StoreLocation.LocalMachine);
            DumpStore(StoreName.Root, StoreLocation.CurrentUser);
            DumpStore(StoreName.Root, StoreLocation.LocalMachine);

            var myNamespace = args[0];
            using var store = new X509Store(
                StoreName.CertificateAuthority,
                StoreLocation.CurrentUser,
                OpenFlags.ReadOnly);
            var k8sConfig = KubernetesClientConfiguration.BuildDefaultConfig();
            k8sConfig.SslCaCerts = store.Certificates;
            var client = new Kubernetes(k8sConfig);
            var pods = client.ListNamespacedPod(myNamespace);
            foreach (var pod in pods.Items)
            {
                Console.WriteLine($"Pod: {pod.Metadata.Name}");
            }
        }
    }
}
```

With proj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="5.0.5" />
  </ItemGroup>

</Project>
```

When run from my console on CentOS 7:

```console
ltheisen@caasd-portal-automation /tmp/InvestigateX509
$ dotnet run pd-auto


Begin CA at CurrentUser


Begin CA at LocalMachine
Cert is: [Subject]
  CN=MITRE BA NPE CA-1, DC=MITRE, DC=ORG

[Issuer]
  CN=MITRE BA ROOT

[Serial Number]
  61042C2D000000000007
...
```

**Comment by tg123** [comment]
hmmm let me check
I do not think kubectl load ca from certstore but it should keep the behavior the same.

I guess the behavior is No CA will fall back to default system ca via .net http call
If so, will make CA optional in config obj

**Comment by WeihanLi** [comment]
Same problem met

**Comment by lucastheisen** [comment]
@tg123, this seems like a relatively small patch with a significant upside (more inline with the `kubectl` client) and no downside i can think of.  Is there reason not to do this?  Do you need a PR, and if we submit one would it be accepted?  The only reason i didn't put one in initially is because its [hard to tell what is generated and what is not](https://github.com/kubernetes-client/csharp/issues/621#issuecomment-841854449).

**Comment by tg123** [comment]
PR is welcomed for sure 
I think adding certstore support is a good idea.

only files in `generated` folder are. those files are with a `warning generated` in the header
