### ISSUE TITLE
Error trying to generate codes

### ISSUE THREAD

**Issue by jack4it** [kubernetes-client/csharp#660]
Following the instructions on README. And got this error consistently. Is this actually the way the codes are generated by the team? I have been trying to make this work and also hopefully also [make the csharp gen works for CRDs](https://github.com/kubernetes-client/gen/issues/195) as well.

```bash
[INFO] VERBOSE [1.18 s]: > Including configuration file 'file:///tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-terraform.md'
[INFO] VERBOSE [1.2 s]: > Including configuration file 'file:///tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/plugin-azure-functions.md'
[INFO] VERBOSE [1.22 s]: > Including configuration file 'file:///tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/graphs.md'
[INFO] VERBOSE [1.24 s]: > Including configuration file 'file:///tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/resources/help-configuration.md'
[INFO] INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210713.3)
[INFO] VERBOSE [1.62 s]: > Including extension configuration file 'file:///tmp/.autorest/@autorest_csharp@3.0.0-beta.20210713.3/node_modules/@autorest/csharp/readme.md'
[INFO] VERBOSE [1.62 s]: > Including configuration file 'file:///tmp/.autorest/@autorest_csharp@3.0.0-beta.20210713.3/node_modules/@autorest/csharp/readme.md'
[INFO] INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.3->4.19.3)
[INFO] VERBOSE [1.76 s]: > Including extension configuration file 'file:///tmp/.autorest/@autorest_modelerfour@4.19.3/node_modules/@autorest/modelerfour/readme.md'
[INFO] VERBOSE [1.76 s]: > Including configuration file 'file:///tmp/.autorest/@autorest_modelerfour@4.19.3/node_modules/@autorest/modelerfour/readme.md'
[INFO] Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
[INFO]   http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
[INFO] Process() cancelled due to exception : [Exception] AutoRest extension '@autorest/csharp' terminated. / Error: [Exception] AutoRest extension '@autorest/csharp' terminated.
[INFO]     at /tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:2028:17
[INFO] [2.01 s] Shutting Down.
[INFO]     at CallbackList.invoke (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100362:39)
[INFO]     at Emitter.fire (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100426:36)
[INFO]     at closeHandler (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:101003:26)
[INFO]     at CallbackList.invoke (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100362:39)
[INFO] [2.01 s] Exiting.
[INFO]     at Emitter.fire (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:100426:36)
[INFO]     at StreamMessageReader.exports.modules.../../../common/temp/node_modules/.pnpm/vscode-jsonrpc@3.6.2/node_modules/vscode-jsonrpc/lib/messageReader.js.AbstractMessageReader.fireClose (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:101797:27)
[INFO]     at Socket.<anonymous> (/tmp/.autorest/@autorest_core@3.1.3/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-e90c84.js:101850:62)
[INFO]     at Socket.emit (events.js:387:35)
[INFO]     at Pipe.<anonymous> (net.js:675:12)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.986 s
[INFO] Finished at: 2021-07-13T20:55:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:exec (generate) on project client-csharp: Result of /bin/sh -c cd / && node --max-old-space-size=8192 /usr/bin/autorest --input-file=/output_dir/swagger.json --csharp --namespace=k8s --package-version=0.0.1 --output-folder=/output_dir --add-credentials --debug --verbose execution is: '1'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tg123** [comment]
pin autorest to ver2
https://github.com/tg123/gen/commit/e8346cefd05b197d5d93feaa1eff5165d354b9cd

**Comment by jack4it** [comment]
oh cool, trying, thx @tg123

**Comment by jack4it** [comment]
now consistently got this new error

```
[INFO] DEBUG: swagger-document-override/md-override-loader - START
[INFO] DEBUG: swagger-document/loader - START
[INFO] DEBUG: pipeline-emitter - START
[INFO] DEBUG: configuration-emitter - START
[INFO] DEBUG: Emitting 'pipeline' at file:///output_dir/pipeline
[INFO] DEBUG: Emitting 'configuration' at file:///output_dir/configuration
[INFO] DEBUG: pipeline-emitter - END
[INFO] DEBUG: configuration-emitter - END
[INFO] DEBUG: swagger-document-override/md-override-loader - END
[INFO] DEBUG: swagger-document/loader - END
[INFO] DEBUG: swagger-document/individual/transform - START
[INFO] Killed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.429 s
[INFO] Finished at: 2021-07-13T22:42:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:exec (generate) on project client-csharp: Result of /bin/sh -c cd / && node --max-old-space-size=8192 /usr/bin/autorest --input-file=/output_dir/swagger.json --csharp --namespace=k8s --package-version=0.0.1 --output-folder=/output_dir --add-credentials --debug --verbose execution is: '137'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:exec (generate) on project client-csharp: Result of /bin/sh -c cd / && node --max-old-space-size=8192 /usr/bin/autorest --input-file=/output_dir/swagger.json --csharp --namespace=k8s --package-version=0.0.1 --output-folder=/output_dir --add-credentials --debug --verbose execution is: '137'.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Result of /bin/sh -c cd / && node --max-old-space-size=8192 /usr/bin/autorest --input-file=/output_dir/swagger.json --csharp --namespace=k8s --package-version=0.0.1 --output-folder=/output_dir --add-credentials --debug --verbose execution is: '137'.
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:283)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tg123** [comment]
start your docker container with 8G+ mem

**Comment by jack4it** [comment]
@tg123 tried that and it worked! thx
