### ISSUE TITLE
ListPodDisruptionBudgetForAllNamespacesAsync throws not found exception.

### ISSUE THREAD

**Issue by kibernetik542** [kubernetes-client/csharp#686]
Hello, 
In my project ListPodDisruptionBudgetForAllNamespacesAsync method always return NotFound, but all other listPods, listPvc etc. everything works fine, kube config file has cluster-admin role.

But with kubectl command we are able to get 2 PDB.

Thanks in advance.

P.S. We are using latest 6.0.1 version with .net 5.0

**Comment by chnyda** [comment]
Can you share your exact code you used to test it @tg123 please?

**Comment by tg123** [comment]
```
   var config = KubernetesClientConfiguration.BuildDefaultConfig();
            IKubernetes client = new Kubernetes(config);
            var all = await client.ListPodDisruptionBudgetForAllNamespacesAsync().ConfigureAwait(false);
            Console.WriteLine(all.Items.Count);

```

**Comment by chnyda** [comment]
With this Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

Using this code:
```var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(kubePath);
            IKubernetes client = new Kubernetes(config);
            var all = await client.ListPodDisruptionBudgetForAllNamespacesAsync().ConfigureAwait(false);
            Console.WriteLine(all.Items.Count);
```

returns 

```
Unhandled exception. Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.ListPodDisruptionBudgetForAllNamespacesWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, Nullable`1 pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListPodDisruptionBudgetForAllNamespacesAsync(IKubernetes operations, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, Nullable`1 pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, CancellationToken cancellationToken)
   at ConsoleApp16.Program.Main(String[] args) in /Users/cedrichnyda/RiderProjects/ConsoleApp16/ConsoleApp16/Program.cs:line 15
   at ConsoleApp16.Program.<Main>(String[] args)

```
I also tried it on a newer Kubernetes version (v1.20.4) and the result is the same

**Comment by tg123** [comment]
6.0.1 is based on 1.22 api spec
could you please try earlier nuget ver or newer k8s server?

**Comment by chnyda** [comment]
We are managing clusters with different versions, so I am afraid downgrading is not possible for us.
We'll find another solution. Thanks a lot.
