### ISSUE TITLE
Cannot list resources using generic client

### ISSUE THREAD

**Issue by chnyda** [kubernetes-client/csharp#688]
When trying to list deployments:

```
            var generic = new GenericClient(config, "", "apps/v1", "deployments");
            var nodes = await generic.ListNamespacedAsync<V1DeploymentList>("kube-system");
```

```
Unhandled exception. Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.ListNamespacedCustomObjectWithHttpMessagesAsync(String group, String version, String namespaceParameter, String plural, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.GenericClient.ListNamespacedAsync[T](String ns, CancellationToken cancel)
   at ConsoleApp16.Program.Main(String[] args) in /Users/cedrichnyda/RiderProjects/ConsoleApp16/ConsoleApp16/Program.cs:line 29
   at ConsoleApp16.Program.<Main>(String[] args)
```

It seems the issue is that the endpoint to be reached is `apis//apps/v1/namespaces/kube-system/deployments` instead of `apis/apps/v1/namespaces/kube-system/deployments`

**Comment by tg123** [comment]
there is a handler to replace `apis//` to `api/`
https://github.com/kubernetes-client/csharp/blob/225bb1f59b650e6849858f52608ef917b2484ddb/src/KubernetesClient/GenericClient.cs#L12


however, this does not handle `apis` well. all will be replaced to `api`. 
I am send a PR to fix it 

Thanks for reporting

**Comment by tg123** [comment]
should be
`var generic = new GenericClient(config, "apps", "v1", "deployments");`

**Comment by chnyda** [comment]
Thanks :)
