### ISSUE TITLE
Error when trying to run Exec example.

### ISSUE THREAD

**Issue by pawelpreczynski-digica** [kubernetes-client/csharp#717]
Hi, 
I'm trying to run example `https://github.com/kubernetes-client/csharp/tree/master/examples/exec`:
`dotnet run`
I got an exception: 
```
Starting Request!
Unhandled exception. System.Net.WebSockets.WebSocketException (2): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at k8s.WebSocketBuilder.BuildAndConnectAsync(Uri uri, CancellationToken cancellationToken) in /home/ppreczynski/Projekty/csharp/src/KubernetesClient/WebSocketBuilder.cs:line 60
   at k8s.Kubernetes.StreamConnectAsync(Uri uri, String invocationId, String webSocketSubProtocol, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /home/ppreczynski/Projekty/csharp/src/KubernetesClient/Kubernetes.WebSocket.cs:line 336
   at exec.Exec.ExecInPod(IKubernetes client, V1Pod pod) in /home/ppreczynski/Projekty/csharp/examples/exec/Exec.cs:line 23
   at exec.Exec.Main(String[] args) in /home/ppreczynski/Projekty/csharp/examples/exec/Exec.cs:line 18
   at exec.Exec.<Main>(String[] args)
```
I expect it to run without error or return more detailed message.

**Comment by brendandburns** [comment]
Exec is trying to upgrade the websocket and the server is throwing a 500 (it really shouldn't do that :)

I would look at the API server logs and find the 500, that should contain more details about what went wrong.
