### ISSUE TITLE
Read Deployment fails with status: operation is canceled since v6.0.9

### ISSUE THREAD

**Issue by jan-pokorny** [kubernetes-client/csharp#742]
Hi, since KubernetesClient 6.0.9 version the method `ReadNamespacedDeploymentAsync` fails all the time with exception: The operation was canceled.
Is it an error or I have to setup something. 
However everything worked till version 6.0.8.

Thanks for an answer.

**Comment by tg123** [comment]
May I  know if you have your own HttpClient?

**Comment by tg123** [comment]
ClientRuntime 2.3.10 -> 2.3.23
should not introduce breaking changes. 

Any testcase I can take a look?

**Comment by jan-pokorny** [comment]
> May I know if you have your own HttpClient?
No, I have not. I use client in the normal way: this.client = new k8s.Kubernetes(this.kubeConfig);

```
		/// <summary>
		/// Get deployment by name.
		/// </summary>
		/// <param name="name">Deployment name.</param>
		/// <param name="namespaceParameter">Namespace.</param>
		/// <returns>Returns deployment information.</returns>
		public async Task<V1Deployment> GetDeploymentAsync(string name, string namespaceParameter = "default")
		{
			name = this.GetValidName(name);

			V1Deployment deployment = null;

			try
			{
				deployment = await this.client.ReadNamespacedDeploymentAsync(name, namespaceParameter);
			}
			catch(HttpOperationException ex)
			{
				this.logger.LogError(ex, "Response: {0}", ex.Response.Content);
			}
			catch(Exception ex)
			{
				this.logger.LogError(ex, ex.Message);
			}

			return deployment;
		}
```

And this ends in Exception as I wrote: The operation was canceled.

**Comment by tg123** [comment]
the Exception means timeout, can you confirm if kubectl works?
and can you confirm downgrade ClientRuntime helps?

**Comment by jan-pokorny** [comment]
Yes, I can confirm it. Any other call is executed well (read pod, read ingress etc.) and I also can confirm that downgrade to version 6.0.8 has made this particular call working again.

**Comment by tg123** [comment]
could you please paste full stack here?

**Comment by jan-pokorny** [comment]
Hi, sorry for delayed answer.

Basically I call something like this:

```
foreach(Environment env) 
{
  Task task = SetStatus(env)
  tasks.Add(task);
}

await Task.WhenAll(tasks);
//---------------------------------------------------
async Task SetState(Environemnt env)
{
  string podName = ComposePodName(env.Name);
  V1Deployment dpl = await k8sOperator.GetDeploymentAsync(podName, env.Namespace);
  if(...)
  ...
}
```


This is stack trace: 
```
   at System.Net.Http.ConnectHelper.<ConnectAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__82.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<GetHttp2ConnectionAsync>d__68.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__72.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsyncCore>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<SendAsyncCore>d__85.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at k8s.Kubernetes.<ReadNamespacedDeploymentWithHttpMessagesAsync>d__325.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at k8s.KubernetesExtensions.<ReadNamespacedDeploymentAsync>d__651.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PlatformApiService.Core.Services.Kubernetes.KubernetesOperator.<GetDeploymentAsync>d__10.MoveNext() in C:\Users\...\KubernetesOperator.cs:line 190
```

**Comment by jan-pokorny** [comment]
Ok, after some tests, if I call await in the loop, it works, but is not going to be fully asynchronous for multiple environments.
Also it doesn't work even when there is only one environment, so only one task is returned and await Task.WhenAll, generally speaking, waits only on one task same way as awaiter directly in the loop.

**Comment by tg123** [comment]
`Task.WhenAll` throws `The operation was canceled`?
This is likely some of the waiting tasks were cancelled by something.

but i do not understand why it has any connection to ClientRuntime.
the library create httpclient only

**Comment by jan-pokorny** [comment]
I've just tested the new version 7.0.5 and .NET 6 and the issue is still there.

> Task.WhenAll throws The operation was canceled?
No. The exeption is thrown directly in the `deployment = await this.client.ReadNamespacedDeploymentAsync(name, namespaceParameter);`
But this is called in the loop I described in previous comment.

Once again the entire case (the line is commented where the exception is thrown):

```C#
		/// <summary>
		/// Set status for all application environments.
		/// </summary>
		/// <param name="dbCollection">App env collection.</param>
		/// <returns></returns>
		public async Task SetAppStatusForAllEnvsAsync(CollectionRes<AdminAppEnvDto> dbCollection)
		{
			if(dbCollection != null && dbCollection.Items.Count > 0)
			{
				List<Task> tasks = new List<Task>();

				IEnumerable<IGrouping<string, AdminAppEnvDto>> groupItems = dbCollection.Items.GroupBy(k => k.KubeConfig);

				foreach(var group in groupItems)
				{
					string kubeConfig = group.Key;
					List<AdminAppEnvDto> items = group.ToList();

					using(KubernetesOperator k8sOperator = new KubernetesOperator(kubeConfig, this.kubeLogger))
					{
						foreach(AdminAppEnvDto item in items)
						{
							Task task = this.SetAppStatusAsync(k8sOperator, item.AppId, item);
							tasks.Add(task);
							//await this.SetAppStatusAsync(k8sOperator, item.AppId, item);
						}
					}

					items.Clear();
				}

				await Task.WhenAll(tasks);
				tasks.Clear();
			}
		}
//------------------------------------------------------------------
		/// <summary>
		/// Set status for application environment.
		/// </summary>
		/// <param name="k8sOperator">K8s operator.</param>
		/// <param name="appId">Application ID.</param>
		/// <param name="appEnv">App environemnt ID.</param>
		/// <returns></returns>
		private async Task SetAppStatusAsync(KubernetesOperator k8sOperator, Guid appId, AdminAppEnvDto appEnv)
		{
			V1Pod pod;
			V1Deployment deployment;

			string podName = this.ComposePodName(appId, appEnv.Name);
			deployment = await k8sOperator.GetDeploymentAsync(podName, appEnv.Namespace);

			if(deployment != null)  // deployment exists in cloud
			{
				...
			}
		}
//--------------------------------------------
		/// <summary>
		/// Get deployment by name.
		/// </summary>
		/// <param name="name">Deployment name.</param>
		/// <param name="namespaceParameter">Namespace.</param>
		/// <returns>Returns deployment information.</returns>
		public async Task<V1Deployment> GetDeploymentAsync(string name, string namespaceParameter = "default")
		{
			name = this.GetValidName(name);

			V1Deployment deployment = null;

			try
			{
				deployment = await this.client.ReadNamespacedDeploymentAsync(name, namespaceParameter);
			}
			catch(HttpOperationException ex)
			{
				this.logger.LogError(ex, "Response: {0}", ex.Response.Content);
			}
			catch(Exception ex) // !!!!!!!!!!!  EXCEPTION: The operation was canceled. !!!!!!!!!!!!!!!!
			{
				this.logger.LogError(ex, ex.Message);
			}

			return deployment;
		}
		
```

**Comment by tg123** [comment]
@jan-pokorny could you please create a test case in e2e test, and I will fix it.

I still cannot understand why `ReadNamespacedDeploymentAsync` throws the exception, seems timeout though.
