### ISSUE TITLE
'System.ComponentModel.Win32Exception (2): No such file or directory' when running in docker

### ISSUE THREAD

**Issue by drdkadtr** [kubernetes-client/csharp#752]
Im trying to run `examples/simple` as described here: https://github.com/dotnet/dotnet-docker/blob/main/samples/run-in-sdk-container.md:

```
# Setup:
$ diff --git i/examples/simple/simple.csproj w/examples/simple/simple.csproj
index 028b76a..426a41a 100755
--- i/examples/simple/simple.csproj
+++ w/examples/simple/simple.csproj
@@ -1,7 +1,7 @@
 <U+FEFF><Project Sdk="Microsoft.NET.Sdk">

   <ItemGroup>
-    <ProjectReference Include="..\..\src\KubernetesClient\KubernetesClient.csproj" />
+    <PackageReference Include="KubernetesClient" Version="6.0.1" />
   </ItemGroup>

   <PropertyGroup>
$ curl -o Directory.Build.props https://raw.githubusercontent.com/dotnet/dotnet-docker/main/samples/Directory.Build.props
``` 

# Attempt to run:

```
$ docker run --rm -it -v $(pwd):/app/ -v $HOME/.kube/config:/root/.kube/config -w /app mcr.microsoft.com/dotnet/sdk:5.0 dotnet run
Starting Request!
Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at k8s.Authentication.GcpTokenProvider.RefreshToken()
   at k8s.Authentication.GcpTokenProvider.GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
   at Microsoft.Rest.TokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedPodAsync(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListNamespacedPod(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nu
```
Any help troubleshooting would be greatly appreciated!

**Comment by tg123** [comment]
GcpTokenProvider depends on a binary `cmd-path` to retrieve the token. 
no such file, here mean `cmd-path`, in your container

**Comment by drdkadtr** [comment]
@tg123 Thx, makes sense. Closing this issue.
