### ISSUE TITLE
Linux Container - No such file or directory

### ISSUE THREAD

**Issue by eflorespalma** [kubernetes-client/csharp#843]
Hi, I am using the library in a linux container, but when it is running it is throwing me the following exception message "**No such file or directory**" and the Stack trace says the following 

```
"at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwNoEx )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at k8s.Authentication.GcpTokenProvider.RefreshToken()
   at k8s.Authentication.GcpTokenProvider.GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
   at k8s.Autorest.TokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.ListDeploymentForAllNamespacesWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, Nullable`1 pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListDeploymentForAllNamespacesAsync(IBasicKubernetes operations, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, Nullable`1 pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, CancellationToken (cancellationToken)
   at CloudManager.Service.Implementation.KubernetesDataService.GetPods(String cluster_name) in /src/CloudManager.Service/Implementation/KubernetesDataService.cs:line 72"
```
Something important to mention is that when I run it locally from my laptop (windows 10) I don't have any problems, since I can connect to the cluster and list the K8S objects.

This is the code I use to make the connection

```
        public Stream GetKubeFile(string cluster_name)
        {
            Stream file = null;
            string KubeFileURL = "PUBLIC_URL"
            using (var cl = new WebClient())
            {
                var content = cl.DownloadData(KubeFileURL);
                file = new MemoryStream(content);
            }
            return file;
        }	


	public async Task<List<dynamic>> GetInfo(string cluster_name)
        {
            try
            {
                var stream = GetKubeFile(cluster_name);

                var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(stream);

                var client = new Kubernetes(config);

		// HERE THE EXCEPTION IS THROW, WHEN  I TRY TO GET THE DEPLOYMENTS
                var microservices = await client.ListDeploymentForAllNamespacesAsync();

                return microservices;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _logger.LogError(ex.StackTrace);
            }
        }
```

These are the docker images used

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
```

As I repeat this works for me locally, but when it is deployed in a linux container I have that exception. I hope you can help me with the problem. Thank you very much.

**Comment by tg123** [comment]
no `gcloud` in your container
see also #752

**Comment by eflorespalma** [comment]
Thk for the response......So I need to install all gcloud cli into my container?. Is there no other way?, because I think that will make my current image too heavy.

**Comment by tg123** [comment]
TODO
better exception message

**Comment by eflorespalma** [comment]
Thanks @brendandburns, I am using the service account credentials.
