### ISSUE TITLE
DeleteNamespacedServiceWithHttpMessagesAsync - k8s.Models.V1ServiceStatus

### ISSUE THREAD

**Issue by atangeman** [kubernetes-client/csharp#847]
Hello,

I am having an issue with the ```DeleteNamespacedServiceWithHttpMessagesAsync``` and ```DeleteNamespacedServiceAsync``` methods. Why are these the only delete methods that return an object of the parent type? ```DeleteNamespacedDeployment```, Container, ConfigMap, etc all return ```V1Status```. 

IntelliSense claims these return a type of ```HttpOperationResponse<V1Service>``` but I receive a serialization error from ```System.Text.Json``` when I attempt to use it.

![image](https://user-images.githubusercontent.com/7134561/166170815-c31f3ce2-0ce6-4179-8710-97d1accc481e.png)

Am I supposed to be using a different JsonSerializer than System.Text? Newtonsoft wasn't working with other aspects of the API client. It's almost as though the actual method is attempting to V1ServiceStatus but the method signature is set to V1Service

Please review

Code:

```
public async Task<HttpOperationResponse<V1Service>> DeleteService(string ns, string name)
{
    return await KubeClient.DeleteNamespacedServiceWithHttpMessagesAsync(name, ns);
}
```

Error:

```
System.Text.Json.JsonException: The JSON value could not be converted to k8s.Models.V1ServiceStatus. Path: $.status | LineNumber: 0 | BytePositionInLine: 67.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
```

**Comment by tg123** [comment]
can you confirm your server version and client version 

this is likely caused by version mismatch

**Comment by tg123** [comment]
see #824
