### ISSUE TITLE
Error while using in latest version of Kubernetes?

### ISSUE THREAD

**Issue by smartaquarius10** [kubernetes-client/csharp#885]
Team,

Working perfectly file in Azure kubernetes 1.19.13 version. But regularly failing in latest versions of AKS. 10 mins back I have spinned up a fresh AKS 1.23.3 version. Without any security, RBAC etc directly using azure portal. 

In addition, I have also spinned up one K3s in my local ubuntu VM in virtual box. But getting this error in both K3s and AKS. Any suggestions. Please. My production is affected badly.

```
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICoreV1Operations.ListNamespacedConfigMapWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.CoreV1OperationsExtensions.ListNamespacedConfigMapAsync(ICoreV1Operations operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, CancellationToken cancellationToken)
   at k8s.CoreV1OperationsExtensions.ListNamespacedConfigMap(ICoreV1Operations operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty)
   at ViewConfigMaps.Program.GetCurrentValue(String configMap, String maintenanceConfigurationKey)
```

Failing at this line
`  var configMaps = client.ListNamespacedConfigMap(Environment.GetEnvironmentVariable("KUBERNETES_NAMESPACE"));`

**Tried with package version 8.0.4 and 5.0.4**

Please help

**Comment by smartaquarius10** [comment]
Sorry.. It worked. I forgot to add role and role binding for the default service account in freshly created kubernetes environments. Due to Azure devops integration these binding are already available in my old 1.19.13 version AKS

For others, please refer [this ](https://stackoverflow.com/questions/56739307/receiving-error-when-calling-kubernetes-api-from-the-pod)doc for hints
