### ISSUE TITLE
YamlException when using BuildConfigFromConfigFile()

### ISSUE THREAD

**Issue by mgernand** [kubernetes-client/csharp#93]
Hi folks,

I was just testing out the .NET Client and got stuck just at the beginning. A YamlException is thrown when I use `KubernetesClientConfiguration.BuildConfigFromConfigFile()`:

**Message**: 
`Property 'as-user-extra' not found on type 'k8s.KubeConfigModels.UserCredentials'.`

**StackTrace**:
```
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
```

I am using the client on a Mac and I am trying to connect to my local Minikube instance.

**`./kube/config`**:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/mgernand/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/mgernand/.minikube/client.crt
    client-key: /Users/mgernand/.minikube/client.key
```

**Package Version**: `0.4.0-beta`

Any ideas?
Cheers, Matt

**Comment by qmfrederik** [comment]
#94 tries to fix this. 

As a workaround, you can either remove the `as-user-extra` line from your kubeconfig file on disk, or read the file as a string, do a `string.Replace("as-user-extra", "#as-user-extra")` and pass the config as a string.
