### ISSUE TITLE
Unable to connect to AKS cluster

### ISSUE THREAD

**Issue by VenkateshSrini** [kubernetes-client/csharp#97]
Hi,
I'm using the Azure AKS cluster for Kubernetes. I find that using the SDK when I connect I get the below error

> System.Net.Http.HttpRequestException
  HResult=0x80072EE7
  Message=An error occurred while sending the request.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at k8s.WatcherDelegatingHandler.<SendAsync>d__0.MoveNext() in D:\Venkatesh\ASPNETCore\2.0\KubernetesSDK\ReadKubeLogs\lib\WatcherDelegatingHandler.cs:line 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at k8s.Kubernetes.<ReadNamespacedPodLogWithHttpMessagesAsync>d__88.MoveNext() in D:\Venkatesh\ASPNETCore\2.0\KubernetesSDK\ReadKubeLogs\lib\generated\Kubernetes.cs:line 13409
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at k8s.KubernetesExtensions.<ReadNamespacedPodLogAsync>d__125.MoveNext() in D:\Venkatesh\ASPNETCore\2.0\KubernetesSDK\ReadKubeLogs\lib\generated\KubernetesExtensions.cs:line 5599
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReadKubeLogs.Service.Controllers.KubeController.<Get>d__2.MoveNext() in D:\Venkatesh\ASPNETCore\2.0\KubernetesSDK\ReadKubeLogs\src\ReadKubeLogs.Service\Controllers\KubeController.cs:line 24
**Inner Exception 1:
WinHttpException: The server name or address could not be resolved**

Version of Kubernetes in AKS is 1.8.1.
I'm using the API `ReadNamespacedPodLogAsync`
I'm able to get response to the same by hitting the uri provided in the server tag through browser (though I get 401 unauthorized as certificates are not present ) which proves that server is reachable.

I'm able to connect to the same using kubectl command also which proves that my AKS cluster does respond to Kubernetes commands

please assist me on the same

**Comment by tg123** [comment]
The server name or address could not be resolved

means that dns cannot resolve your domain name
cloud you please paste output of

nslookup yourhost

**Comment by VenkateshSrini** [comment]
Hi,
I got the below response
Server:  UnKnown
Address:  fe80::261f:a0ff:fec4:7109

Non-authoritative answer:
Name:    ifttt-demo-kube-faas-rg-eea6d7-7d1fd319.hcp.eastus.azmk8s.io
Address:  52.186.82.246

But if you could see I'm able to execute kubectl commands without any issues
also https://ifttt-demo-kube-faas-rg-eea6d7-7d1fd319.hcp.eastus.azmk8s.io is very much accessible from browser

**Comment by VenkateshSrini** [comment]
@tg123 ,
Any guidance for me on the same ?

**Comment by tg123** [comment]
@VenkateshSrini  I tested using your domain name I cannot reproduce your issue
are you using any proxy in your .net program?

**Comment by VenkateshSrini** [comment]
@tg123,
I'm still not able to connect. I'm using a. Net core web api app. Can you please share the code that you had used to test. I will try to see where the difference is. Alternatively I can also check-in my code to git hub and share you a link. Please tell me which will work for you

**Comment by tg123** [comment]
```
       IKubernetes client = new Kubernetes(new KubernetesClientConfiguration
            {
                Host = "https://ifttt-demo-kube-faas-rg-eea6d7-7d1fd319.hcp.eastus.azmk8s.io",
                SkipTlsVerify = true
            });
            var list = client.ListNamespacedPod("default"); //401 here 
```

**Comment by VenkateshSrini** [comment]
@tg123 
1) Can you please tell me what is the mistake I'm doing in the attached code. I still get the above error
2) Even If I give the correct Cert data , key and access token I'm still getting unauthorized error with AKS. The same works with kubectl . please hel
[ReadKubeLogs.Service.zip](https://github.com/kubernetes-client/csharp/files/1777110/ReadKubeLogs.Service.zip)

**Comment by tg123** [comment]
I will check it later I am on travel

2018年3月3日(土) 12:51 VenkateshSrini <notifications@github.com>:

**Comment by VenkateshSrini** [comment]
@tg123,
I have found the issue. It was with wrong access token. Thanks for helping me. Happy and successful travel to you
